FROM rocker/r2u

# Add system library dependencies
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     # RPostgres package requirements
#     libpq-dev \
#     libssl-dev \
#     # httpuv package requirement
#     libz-dev \
#     # curl package requirement
#     libcurl4-openssl-dev \
#     # xlm2 package requirement
#     libxml2-dev \
#     # httpgd package requirement (VS Code development package)
#     libfontconfig1-dev \
# && rm -rf /var/lib/apt/lists/*